### ISSUE TITLE
Which implementation of forbes do you use?

### ISSUE THREAD

**Issue by endrebak** [hyperbrowser/pycolocstats#12]
I have tried searching the repo for forbes, but I get no results :)

What package do you use for computing the Forbes coefficient?

I'd love to implement an all-python version of it for my https://github.com/biocore-ntnu/pyranges package, but a reference implementation to test against would be helpful :)

**Comment by ivargr** [comment]
I guess @borissim would know how and where it is implemented, but if you want to implement it in Python, it should be fairly straight forward to do so whitout any package, since Forbes is just the number of basepairs overlap divided by "expected" number of base pairs overlap. You'll find the exact formula here under the section "Similarity measures": https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbz083/5586919

**Comment by endrebak** [comment]
Thanks! I threw together an implementation, but warned users that it is experimental:

```
forbes = chromsizes_sum * intersection_sum / (reference_length * query_length)
```

I'd love to implement the `tetrachoric` correlation too, but it seems much more involved. If you know a simple-ish implementation please post a link.
